azure:
  storage:
    container:
      name: dXNlcnBpY3R1cmU=
    connection:
      string: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPW5ld3NhcHBpbWFnZTtBY2NvdW50S2V5PWdHL21MU1VRVXJKQ0NZbU8yVG9qWkJvRlRDOHMzNkcxRGhiNlRiZExXYVVhNTNtT0MxSUN4Y3oyWGt4Z042VlVWdWtiV3ppVjRjcFArQVN0U1N2bmdRPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==