# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest
    environment: NOTElysia HP Arch Linux Server

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Upload code to homelab server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOMELAB_HOST }}
        username: ${{ secrets.HOMELAB_USER }}
        port: ${{ secrets.HOMELAB_PORT }}
        key: ${{ secrets.HOMELAB_KEY }}
        source: "target/lib,target/restservices-2.0.jar"
        target: "/home/${{ secrets.HOMELAB_USER }}/Documents/RESTComplied"
    - name: Post config for services
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOMELAB_HOST }}
        username: ${{ secrets.HOMELAB_USER }}
        port: ${{ secrets.HOMELAB_PORT }}
        key: ${{ secrets.HOMELAB_KEY }}
        script: "/home/${{ secrets.HOMELAB_USER }}/Documents/RESTComplied/postconfig.sh"
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4.0.0
    - name: GitHub Actions Discord Webhook
    # You may pin to the exact commit or the version.
    # uses: nebularg/actions-discord-webhook@633ae6b03882743988dbc992eb147818ca96a93e
      uses: nebularg/actions-discord-webhook@v1.0.0
      with:
        # The Discord webhook url
        webhook_url: https://discord.com/api/webhooks/1218651145015267568/cQfg2bvecKcDqaxSacOrZGxG-mIPOM9s0Yq4XkuItYJzUAzqoOky97CgbOvHIPIJvrRE
        # The build status
        status: ${{ job.status }}
          
